name: ChunkMirrored
version: '1.0-SNAPSHOT'
main: de.kilip.chunkMirrored.ChunkMirrored
api-version: '1.21'
depend: [Citizens]
commands:
  tpc:
    description: Teleports you to the Chunk of another player
    usage: /tpc
    permission: ChunkMirrored.tpc